### ISSUE TITLE
Contract available to deploy on Arbitrum One?

### ISSUE THREAD

**Issue by lazydefi1** [1inch/multicall#6]
Is the source of the contract available?

**Comment by clostao** [comment]
I've been testing the package using networks like Testnet Ropsten or Avalanche (with other multicall smart contracts) and neither of them works. What I get is execution reverted. It'd be great to have the contract deployed in those networks, or at least having the smart contract code available so then we can deploy them.

In the case none of this is possible, there are some compatibles multicall smart contracts in these networks that would substitute the @1inch/multicall ones?

**Comment by krboktv** [comment]
As for the contract source code, you can look at the etherescan's verified code section:
https://etherscan.io/address/0x8d035edd8e09c3283463dade67cc0d49d6868063#code

Regarding the deployment of  Avalanche, Gnosis Chain, Arbitrium One contracts, you can look at the README
